"""Data access for the powercalc package.

Loads the baked snapshot (data/powercalc-data.json) and provenance
(data/provenance.json). The snapshot is generated by the extraction
pipeline (skill: motortown-pak-mod-build, reference
engine-power-torque-model.md) and committed to the repo -- it is the
single source of truth for the running tool; regenerate + PR when the
game or MoreTuning updates.

Snapshot schema (powercalc-data/2):
  curves                 name -> [[time, value, interp, arrive_t, leave_t], ...]
  engines                asset name -> engine DataAsset fields (+ curve_keys attached at load)
  parts                  part id -> {type: Intake|Turbocharger, ...struct, cost}
  engine_parts           part id -> {type: Engine, engine_asset, mass_kg, category, cost, ...}
  vehicle_default_engine vehicle id -> default engine part id
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_DATA_DIR = Path(__file__).parent / "data"

CATEGORY_ORDER = ("car", "pickup", "truck", "bike")


class PartNotFound(KeyError):
    pass


@lru_cache(maxsize=1)
def _snapshot() -> dict:
    with open(_DATA_DIR / "powercalc-data.json", encoding="utf-8") as f:
        data = json.load(f)
    # attach resolved curve keys to every engine dict so model.compute() can run
    curves = data["curves"]
    for eng in data["engines"].values():
        curve_name = eng.get("curve")
        if curve_name in curves:
            eng["curve_keys"] = curves[curve_name]
    return data


@lru_cache(maxsize=1)
def provenance() -> dict:
    with open(_DATA_DIR / "provenance.json", encoding="utf-8") as f:
        return json.load(f)


def data_version() -> str:
    return str(provenance().get("data_version", "unknown"))


def model_version() -> str:
    return str(provenance().get("model_version", "unknown"))


def engine_asset(asset_name: str) -> dict:
    engines = _snapshot()["engines"]
    if asset_name not in engines:
        raise PartNotFound(asset_name)
    return engines[asset_name]


def engine_part(part_id: str) -> dict:
    parts = _snapshot()["engine_parts"]
    if part_id not in parts:
        raise PartNotFound(part_id)
    return parts[part_id]


def resolve_engine(part_id: str) -> tuple[dict, dict]:
    """Engine part row + its engine-asset dict (curve keys attached)."""
    row = engine_part(part_id)
    asset_name = row.get("engine_asset") or ""
    return row, engine_asset(asset_name)


def intake_part(part_id: str) -> dict | None:
    """Intake struct for an intake part id; None = stock intake."""
    if part_id in (None, "", "(stock)"):
        return None
    parts = _snapshot()["parts"]
    row = parts.get(part_id)
    if not row or row.get("type") != "Intake":
        raise PartNotFound(part_id)
    return row.get("intake")


def turbo_part(part_id: str) -> dict | None:
    """Turbo struct for a turbo part id; None = no turbo (NA)."""
    if part_id in (None, "", "(none)"):
        return None
    parts = _snapshot()["parts"]
    row = parts.get(part_id)
    if not row or row.get("type") != "Turbocharger":
        raise PartNotFound(part_id)
    return row.get("turbocharger")


def intake_ids() -> list[str]:
    return sorted(p for p, v in _snapshot()["parts"].items() if v.get("type") == "Intake")


def turbo_ids() -> list[str]:
    return sorted(p for p, v in _snapshot()["parts"].items() if v.get("type") == "Turbocharger")


def engine_part_ids(
    category: str | None = None,
    min_mass: float | None = None,
    max_mass: float | None = None,
) -> list[str]:
    out = []
    for pid, row in _snapshot()["engine_parts"].items():
        if category and row.get("category") != category:
            continue
        mass = row.get("mass_kg") or 0.0
        if min_mass is not None and mass < min_mass:
            continue
        if max_mass is not None and mass > max_mass:
            continue
        out.append(pid)
    return sorted(out)


def part_cost(part_id: str) -> int:
    """Part-row Cost field for any part id (engine/intake/turbo). 0 if absent."""
    snap = _snapshot()
    row = snap["engine_parts"].get(part_id) or snap["parts"].get(part_id)
    if not row:
        return 0
    return int(row.get("cost") or 0)


def default_engine_for(vehicle_id: str) -> str:
    vde = _snapshot()["vehicle_default_engine"]
    if vehicle_id not in vde:
        raise PartNotFound(vehicle_id)
    return vde[vehicle_id]
