# Generated by Django

from django.db import migrations
from django.contrib.gis.geos import Point
from decimal import Decimal

# Helper to create/get area from point
def get_area_from_point(SubsidyArea, DeliveryPoint, point_name, buffer_dist=100, area_name=None):
    if area_name is None:
        area_name = point_name
    
    # Try to find existing area first? 
    if SubsidyArea.objects.filter(name=area_name).exists():
        return SubsidyArea.objects.get(name=area_name)

    point_obj = DeliveryPoint.objects.filter(name=point_name).first()
    if not point_obj:
        print(f"Warning: DeliveryPoint '{point_name}' not found. Skipping area creation.")
        return None
    
    # Create buffered polygon
    try:
        # buffer_dist units depends on SRID. 3857 is meters.
        poly = point_obj.coord.buffer(buffer_dist)
        if hasattr(poly, 'srid') and poly.srid != 3857:
             poly.srid = 3857
             
        area = SubsidyArea.objects.create(
            name=area_name,
            polygon=poly,
            description=f"Generated from '{point_name}'"
        )
        return area
    except Exception as e:
        print(f"Error creating area for {point_name}: {e}")
        return None

def populate_subsidies(apps, schema_editor):
    SubsidyRule = apps.get_model('amc', 'SubsidyRule')
    SubsidyArea = apps.get_model('amc', 'SubsidyArea')
    DeliveryPoint = apps.get_model('amc', 'DeliveryPoint')
    Cargo = apps.get_model('amc', 'Cargo')

    # ensure cargos exist
    cargos = {
        'Burger_01_Signature': 'Signature Burger',
        'Pizza_01_Premium': 'Premium Pizza',
        'LiveFish_01': 'Live Fish',
        'AirlineMealPallet': 'Airline Meal Pallet',
        'Log_Oak_12ft': '12ft Oak Log',
        'Coal': 'Coal',
        'Iron Ore': 'Iron Ore',
        'WoodPlank_14ft_5t': 'Wood Plank 14ft 5t',
        'Fuel': 'Fuel',
        'BottlePallete': 'Water Bottle Pallete',
        'MeatBox': 'Meat Box',
        'TrashBag': 'Trash Bag',
        'Trash_Big': 'Big Trash',
    }
    
    cargo_objs = {}
    for key, label in cargos.items():
        obj, _ = Cargo.objects.get_or_create(key=key, defaults={'label': label})
        cargo_objs[key] = obj

    # 1. Burger/Pizza/Fish - 300% on time
    rule = SubsidyRule.objects.create(
        name="Burger/Pizza/Fish Priority",
        reward_type='PERCENTAGE',
        reward_value=Decimal('3.0'),
        active=True,
        requires_on_time=True,
        priority=10
    )
    rule.cargos.add(cargo_objs['Burger_01_Signature'])
    rule.cargos.add(cargo_objs['Pizza_01_Premium'])
    rule.cargos.add(cargo_objs['LiveFish_01'])

    # 2. Airline Meals - 200% on time
    rule = SubsidyRule.objects.create(
        name="Airline Meals",
        reward_type='PERCENTAGE',
        reward_value=Decimal('2.0'),
        active=True,
        requires_on_time=True,
        priority=10
    )
    rule.cargos.add(cargo_objs['AirlineMealPallet'])

    # 3. Oak Log - 250% damage scale
    rule = SubsidyRule.objects.create(
        name="Oak Logs",
        reward_type='PERCENTAGE',
        reward_value=Decimal('2.5'),
        active=True,
        scales_with_damage=True,
        priority=10
    )
    rule.cargos.add(cargo_objs['Log_Oak_12ft'])

    # 4. Coal/Iron Ore - 150% (Gwangjin Mine -> Gwangjin Storage)
    area_coal = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Coal")
    area_iron_mine = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Iron Ore Mine")
    area_iron_storage = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Iron Ore Storage")
    area_coal_storage = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Coal Storage")
    
    if any([area_coal, area_iron_mine]) and any([area_iron_storage, area_coal_storage]):
        rule = SubsidyRule.objects.create(
            name="Gwangjin Coal/Iron Logistics",
            reward_type='PERCENTAGE',
            reward_value=Decimal('1.5'),
            priority=15
        )
        rule.cargos.add(cargo_objs['Coal'])
        rule.cargos.add(cargo_objs['Iron Ore'])
        if area_coal: rule.source_areas.add(area_coal)
        if area_iron_mine: rule.source_areas.add(area_iron_mine)
        if area_iron_storage: rule.destination_areas.add(area_iron_storage)
        if area_coal_storage: rule.destination_areas.add(area_coal_storage)

    # 5. Planks - 250%
    area_plank_storage = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Plank Storage")
    area_oak1 = get_area_from_point(SubsidyArea, DeliveryPoint, "Migeum Oak 1")
    area_oak2 = get_area_from_point(SubsidyArea, DeliveryPoint, "Migeum Oak 2")
    area_oak3 = get_area_from_point(SubsidyArea, DeliveryPoint, "Migeum Oak 3")

    if area_plank_storage:
        rule = SubsidyRule.objects.create(
            name="Gwangjin Planks Logistic",
            reward_type='PERCENTAGE',
            reward_value=Decimal('2.5'),
            priority=15
        )
        rule.cargos.add(cargo_objs['WoodPlank_14ft_5t'])
        rule.source_areas.add(area_plank_storage)
        for a in [area_coal, area_iron_mine, area_oak1, area_oak2, area_oak3]:
            if a: rule.destination_areas.add(a)

    # 6. Fuel - 150%
    area_fuel_storage = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Fuel Storage")
    if area_fuel_storage:
         rule = SubsidyRule.objects.create(
            name="Gwangjin Fuel Supply",
            reward_type='PERCENTAGE',
            reward_value=Decimal('1.5'),
            priority=15
        )
         rule.cargos.add(cargo_objs['Fuel'])
         rule.source_areas.add(area_fuel_storage)
         if area_coal: rule.destination_areas.add(area_coal)
         if area_iron_mine: rule.destination_areas.add(area_iron_mine)

    area_log_warehouse = get_area_from_point(SubsidyArea, DeliveryPoint, "Migeum Log Warehouse")
    if area_log_warehouse:
         rule = SubsidyRule.objects.create(
            name="Migeum Fuel Supply",
            reward_type='PERCENTAGE',
            reward_value=Decimal('1.5'),
            priority=15
        )
         rule.cargos.add(cargo_objs['Fuel'])
         rule.source_areas.add(area_log_warehouse)
         for a in [area_oak1, area_oak2, area_oak3]:
             if a: rule.destination_areas.add(a)

    # 7. Water Bottle Pallets 
    area_gwangjin_market = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Supermarket")
    area_ara_market = get_area_from_point(SubsidyArea, DeliveryPoint, "Ara Supermarket")
    
    if any([area_gwangjin_market, area_ara_market]):
        rule_wb_300 = SubsidyRule.objects.create(
            name="Water Global Shortage (High)",
            reward_type='PERCENTAGE',
            reward_value=Decimal('3.0'),
            priority=12
        )
        rule_wb_300.cargos.add(cargo_objs['BottlePallete'])
        if area_gwangjin_market: rule_wb_300.destination_areas.add(area_gwangjin_market)
        if area_ara_market: rule_wb_300.destination_areas.add(area_ara_market)
    
    supermarket_points = DeliveryPoint.objects.filter(name__icontains="Supermarket")
    if supermarket_points.exists():
         rule_wb_200 = SubsidyRule.objects.create(
            name="Water Supply (Standard)",
            reward_type='PERCENTAGE',
            reward_value=Decimal('2.0'),
            priority=10
         )
         rule_wb_200.cargos.add(cargo_objs['BottlePallete'])
         
         rule_meat = SubsidyRule.objects.create(
            name="Meat Supply",
            reward_type='PERCENTAGE',
            reward_value=Decimal('2.0'),
            priority=10
         )
         rule_meat.cargos.add(cargo_objs['MeatBox'])

         for dp in supermarket_points:
             area = get_area_from_point(SubsidyArea, DeliveryPoint, dp.name)
             if area:
                 rule_wb_200.destination_areas.add(area)
                 rule_meat.destination_areas.add(area)
                 
    # 8. Trash
    ara_p = Point(x=329486.94, y=1293697.78, z=-18594.89, srid=3857)
    ara_trash_area = SubsidyArea.objects.create(
        name="Ara Trash Zone",
        polygon=ara_p.buffer(180_000), 
        description="Legacy trash zone for Ara (radius 180000)"
    )
    rule_trash_ara = SubsidyRule.objects.create(
        name="Ara Trash Subsidy",
        reward_type='PERCENTAGE',
        reward_value=Decimal('2.0'),
        priority=12
    )
    rule_trash_ara.cargos.add(cargo_objs['TrashBag'])
    rule_trash_ara.cargos.add(cargo_objs['Trash_Big'])
    rule_trash_ara.destination_areas.add(ara_trash_area)
    
    gwangjin_p = Point(x=318700.36, y=816972.24, z=-1636.26, srid=3857)
    gwangjin_trash_area = SubsidyArea.objects.create(
        name="Gwangjin Trash Zone",
        polygon=gwangjin_p.buffer(200_000),
        description="Legacy trash zone for Gwangjin (radius 200000)"
    )
    rule_trash_gw = SubsidyRule.objects.create(
        name="Gwangjin Trash Subsidy",
        reward_type='PERCENTAGE',
        reward_value=Decimal('2.5'),
        priority=13
    )
    rule_trash_gw.cargos.add(cargo_objs['TrashBag'])
    rule_trash_gw.cargos.add(cargo_objs['Trash_Big'])
    rule_trash_gw.destination_areas.add(gwangjin_trash_area)
    
    # 9. Gwangjin Supermarket General Catch-all (300%)
    if area_gwangjin_market:
        rule_catchall = SubsidyRule.objects.create(
            name="Gwangjin Supermarket Stimulus",
            reward_type='PERCENTAGE',
            reward_value=Decimal('3.0'),
            priority=5 
        )
        rule_catchall.destination_areas.add(area_gwangjin_market)
        
        area_gs = get_area_from_point(SubsidyArea, DeliveryPoint, "Gwangjin Supermarket Gas Station")
        if area_gs: rule_catchall.destination_areas.add(area_gs)


def remove_subsidies(apps, schema_editor):
    SubsidyRule = apps.get_model('amc', 'SubsidyRule')
    names = [
        "Burger/Pizza/Fish Priority",
        "Airline Meals",
        "Oak Logs",
        "Gwangjin Coal/Iron Logistics",
        "Gwangjin Planks Logistic",
        "Gwangjin Fuel Supply",
        "Migeum Fuel Supply",
        "Water Global Shortage (High)",
        "Water Supply (Standard)",
        "Meat Supply",
        "Ara Trash Subsidy",
        "Gwangjin Trash Subsidy",
        "Gwangjin Supermarket Stimulus"
    ]
    SubsidyRule.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0135_subsidyarea_alter_deliverypoint_coord_subsidyrule'),
    ]

    operations = [
        migrations.RunPython(populate_subsidies, reverse_code=remove_subsidies),
    ]
