# Generated by Django 5.2.3 on 2026-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0215_guild_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildpassengerrequirement',
            name='fugitive_chance',
            field=models.FloatField(default=0.0, help_text='Probability (0.0–1.0) that a matched passenger is a fugitive, triggering Wanted status.'),
        ),
        migrations.AlterField(
            model_name='guildcargorequirement',
            name='bonus_pct',
            field=models.FloatField(default=0, help_text='Bonus percentage applied to payment when criteria are met (e.g. 10 = +10%).'),
        ),
        migrations.AlterField(
            model_name='guildpassengerrequirement',
            name='bonus_pct',
            field=models.FloatField(default=0, help_text='Bonus percentage applied to payment when criteria are met (e.g. 10 = +10%).'),
        ),
    ]
