# Generated by Django 5.2.3 on 2026-05-04 17:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_sessions_for_existing_rp_characters(apps, schema_editor):
    Character = apps.get_model("amc", "Character")
    RPSession = apps.get_model("amc", "RPSession")
    now = django.utils.timezone.now()
    past = now - datetime.timedelta(hours=2)
    for char in Character.objects.filter(rp_mode=True):
        RPSession.objects.create(character=char, created_at=past, expires_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0217_serverstatus_fd_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = active session. Set when the player toggles RP mode off.', null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_sessions', to='amc.character')),
            ],
            options={
                'indexes': [models.Index(fields=['character', 'expires_at'], name='amc_rpsessi_charact_5cfef8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('expires_at__isnull', True)), fields=('character',), name='unique_active_rp_session_per_character')],
            },
        ),
        migrations.RunPython(
            create_sessions_for_existing_rp_characters,
            migrations.RunPython.noop,
        ),
    ]
