# Generated by Django 5.2.3 on 2026-05-05 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0218_rp_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_key', models.CharField(blank=True, help_text='House GUID — null means applies to all houses', max_length=100, null=True)),
                ('rebate_pct', models.DecimalField(decimal_places=2, default=100, help_text='Rebate percentage (0–100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_licenses', to='amc.character')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rebate_pct__gte', 0), ('rebate_pct__lte', 100)), name='housing_license_rebate_pct_between_0_100')],
            },
        ),
    ]
