# Generated by Django 5.2.3 on 2026-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0219_housinglicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='DataTable RowName (e.g. GimNyungBeach_01)', max_length=100, unique=True)),
                ('cost', models.PositiveIntegerField(help_text='Base house cost from FMTHouseRow.Cost')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
