# Generated by Django 5.2.3 on 2026-05-07 14:56
# House costs extracted from MotorTown v0.7.18+1 Houses DataTable via mt-pak-extract.

from django.db import migrations

# Source: out/Houses_parsed.json — RowName -> Cost
# Deduplicated (two "BuildingTest" rows exist in the DataTable with Cost=1000).
HOUSE_DATA = [
    ("Aewol_01", 50000),
    ("Ara_01", 200000),
    ("Baram_01", 250000),
    ("Biyang_01", 150000),
    ("Biyang_02", 300000),
    ("BuildingTest", 1000),
    ("CheonJin_01", 100000),
    ("CheonJin_02", 100000),
    ("Daejin_01", 100000),
    ("Dongsan_01", 120000),
    ("Downtown_01", 300000),
    ("Downtown_02", 280000),
    ("Downtown_03", 400000),
    ("FirstHouse", 300000),
    ("Gaon_01", 200000),
    ("Gapa_01", 100000),
    ("Gapa_02", 50000),
    ("GimNyungBeach_01", 200000),
    ("Gujwa_01", 500000),
    ("Gujwa_ContainerHouse", 30000),
    ("Gwangjin_01", 300000),
    ("Gwangjin_02", 250000),
    ("GwangjinTown_01", 180000),
    ("GwangjinTown_02", 250000),
    ("Hallim_01", 80000),
    ("HousingTest_House0", 100),
    ("JoCheon_01", 30000),
    ("Lake_01", 80000),
    ("Obo_01", 300000),
    ("Obo_02", 300000),
    ("Oedo_01", 50000),
    ("PyoSun_01", 80000),
    ("Sanho_01", 300000),
    ("Sanho_02", 150000),
    ("SeoGuiPo_WestTown_01", 200000),
    ("SeoGuiPo_WestTown_02", 350000),
    ("SinChang_01", 100000),
    ("SungSan_01", 50000),
]


def populate_houses(apps, schema_editor):
    House = apps.get_model("amc", "House")
    House.objects.bulk_create(
        [House(key=key, cost=cost) for key, cost in HOUSE_DATA],
        ignore_conflicts=True,
    )


def reverse(apps, schema_editor):
    House = apps.get_model("amc", "House")
    House.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("amc", "0220_add_house_model"),
    ]

    operations = [
        migrations.RunPython(populate_houses, reverse),
    ]
