# Generated by Django 5.2.3 on 2026-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0221_populate_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjob',
            name='bonus_multiplier',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryjobtemplate',
            name='bonus_multiplier',
            field=models.FloatField(default=0),
        ),
    ]
