# Generated by Django 5.2.3 on 2026-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0222_deprecate_bonus_multiplier_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='expiration_processed',
            field=models.BooleanField(default=False, help_text='True after cleanup_expired_jobs has paid out partial contributors'),
        ),
    ]
