# Generated by Django 5.2.3 on 2026-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amc", "0230_jobpostingconfig_min_active_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namemoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("rename", "Rename"),
                    ("none", "None"),
                    ("manual_review", "Manual Review"),
                    ("whitelist", "Whitelist"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="namemoderationlog",
            name="verdict_source",
            field=models.CharField(
                choices=[
                    ("blocklist", "Blocklist"),
                    ("llm", "Llm"),
                    ("cache", "Cache"),
                    ("error", "Error"),
                    ("whitelist", "Whitelist"),
                ],
                max_length=16,
            ),
        ),
    ]
