# Generated by Django 5.0.7 on 2026-08-17 00:00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amc", "0231_alter_namemoderationlog_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="forced_rp_until",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "While in the future, the player is locked into RP mode and "
                    "cannot toggle it off until this time. NULL = not forced."
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ForcedRPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("set", "Set"), ("clear", "Clear")], max_length=10
                    ),
                ),
                ("old_until", models.DateTimeField(blank=True, null=True)),
                ("new_until", models.DateTimeField(blank=True, null=True)),
                (
                    "actor_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="amc.character",
                    ),
                ),
                (
                    "actor_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="amc.player",
                    ),
                ),
                (
                    "actor_discord_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forced_rp_logs",
                        to="amc.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]