# Generated by Django 5.2.3 on 2026-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0236_exclusiveprogressionbreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namemoderationlog',
            name='action',
            field=models.CharField(choices=[('rename', 'Rename'), ('none', 'None'), ('manual_review', 'Manual Review'), ('whitelist', 'Whitelist'), ('undone', 'Undone')], default='none', max_length=16),
        ),
    ]
