# Generated by Django 5.2.3 on 2026-09-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0239_servercargoarrivedlog_delivery_id'),
        ('amc', '0239_worldobject_tag_notes'),
    ]

    operations = [
    ]
