# Generated by Django 5.2.3 on 2026-09-21 16:40, renumbered onto 0246_exam_models

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0246_exam_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompassTuningConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='A', help_text='Label of which tuning preset (A, B, ...) these values match.', max_length=8)),
                ('c', models.FloatField(default=3e-06, help_text='Compass frequency constant: Hz per (metre * km/h). Higher = faster everywhere.')),
                ('min_interval', models.FloatField(default=3.0, help_text='SOLO floor in seconds (fastest possible bearing per cop).')),
                ('max_interval', models.FloatField(default=15.0, help_text='SOLO ceiling in seconds (parked suspect); also the <200m close-ping interval.')),
                ('ring_distance', models.IntegerField(default=20000, help_text="Close-ring distance in game units (100 units = 1 m; 20000 = 200 m). Inside: fixed '<200m' ping, no bearing.")),
                ('budget_cap', models.PositiveSmallIntegerField(default=2, help_text='Force-budget cap: interval is multiplied by min(N, cap).', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Compass Tuning Configuration',
                'verbose_name_plural': 'Compass Tuning Configuration',
            },
        ),
    ]
