# Generated by Django 5.2.3 on 2026-09-22 07:41

from django.db import migrations, models


def mark_first_row_active(apps, schema_editor):
    CompassTuningConfig = apps.get_model("amc", "CompassTuningConfig")
    row = CompassTuningConfig.objects.first()
    if row and not CompassTuningConfig.objects.filter(active=True).exists():
        row.active = True
        row.save(update_fields=["active"])


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0248_wantedsystemconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compasstuningconfig',
            options={'verbose_name': 'Compass Tuning Configuration', 'verbose_name_plural': 'Compass Tuning Configurations'},
        ),
        migrations.AddField(
            model_name='compasstuningconfig',
            name='active',
            field=models.BooleanField(default=False, help_text='The configuration the compass tick actually uses. Only one row may be active.'),
        ),
        migrations.AddConstraint(
            model_name='compasstuningconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active_compass_tuning'),
        ),
        migrations.RunPython(mark_first_row_active, migrations.RunPython.noop),
    ]
