# Generated by Django 5.2.3 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0249_compass_tuning_multi_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='no_teleport',
            field=models.BooleanField(default=False, help_text='Teleport-locked server-side via the mod\'s invisible no-teleport flag.'),
        ),
    ]
