# Generated by Django 5.2.3 on 2026-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0255_merge_0254_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsystemconfig',
            name='police_required',
            field=models.BooleanField(default=True, help_text='ON (default): zero effective cops on duty puts the wanted system dormant — no organic triggers, active organic wanteds cleared. OFF: wanted triggers fire and heat moves with zero cops on duty; the distance law treats police distance as infinite (decay F(D)=3.0x, growth A(D)=1/3x).'),
        ),
    ]
