# Generated by Django 5.2.3 on 2026-09-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0261_gameevent_race_legality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='origin',
            field=models.CharField(blank=True, help_text="What triggered this wanted: NULL = illicit cargo, 'fugitive_passenger' = guild fugitive passenger, 'event_race' = illegal-race event enforcement (Yuuka 2026-09-27). Fugitive-origin records are exempt from the dormant amnesty — they persist through dormant ticks and resume normal decay once a cop is back on duty (Hamster 2026-09-27). Event-race origin shares the dormant exemption (the race IS the enforcement, cops or not).", max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='PoliceWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_confiscated_total', models.PositiveBigIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin player who added this entry (via /police_whitelist).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='amc.player')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_whitelist', to='amc.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'police_confiscated_total'], name='amc_policew_player__0b1c8b_idx')],
            },
        ),
    ]
