# Generated by Django 5.2.3 on 2026-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0261_gameevent_race_legality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='origin',
            field=models.CharField(blank=True, help_text="What triggered this wanted: NULL = illicit cargo, 'fugitive_passenger' = guild fugitive passenger, 'event_race' = illegal-race event enforcement (Yuuka 2026-09-27). Fugitive-origin records are exempt from the dormant amnesty — they persist through dormant ticks and resume normal decay once a cop is back on duty (Hamster 2026-09-27). Event-race origin shares the dormant exemption (the race IS the enforcement, cops or not).", max_length=32, null=True),
        ),
    ]
