# Generated by Django 5.2.3 on 2026-10-04

import amc.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amc", "0265_scheduled_event_allowed_vehicle_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledevent",
            name="allowed_vehicle_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=amc.models._default_underground_vehicle_types,
                help_text=(
                    "Allowed vehicle types (Yuuka 2026-10-04: default Small + "
                    "Pickup for ALL new SEs); empty = inherit the pinned HP "
                    "class's list"
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="ttclass",
            name="allowed_vehicle_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=amc.models._default_underground_vehicle_types,
                help_text=(
                    "Vehicle types allowed in races of this class. Values are "
                    "gamedata vehicle_type strings (Small, Pickup, Truck, "
                    "SemiTractor, SemiTrailer, Bus, SmallTrailer, Bike, Kart, "
                    "HeavyMachinery, Racecar, Motorhome). Fail-closed: an "
                    "unmapped vehicle type is always a violation."
                ),
                size=None,
            ),
        ),
    ]
